services:
  - type: web
    name: aerotrack
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: API_HOST
        value: 0.0.0.0
      - key: AEROTRACK_MODEL_PATH
        value: /app/models/aerotrack-detector-demo-v2.pt
      - key: AEROTRACK_MODEL_URL
        sync: false
      - key: AEROTRACK_DEVICE
        value: cpu
      - key: AEROTRACK_CONFIDENCE
        value: "0.25"
      - key: AEROTRACK_IOU
        value: "0.45"
      - key: AEROTRACK_PREDICT_IMGSZ
        value: "512"
      - key: AEROTRACK_TRACK_MAX_FRAMES
        value: "4"
      - key: AEROTRACK_OUTPUT_DIR
        value: /app/outputs
      - key: MLFLOW_UI_URL
        sync: false
